### ISSUE TITLE
Reconfigure main.py to allow for command line arguments

### ISSUE THREAD

**Issue by taytayp** [BostonCyclistsUnion/StressMap#13]
Going in to the `main.py` script to edit fields to select which area to analyze is a bit cumbersome, so I propose we instead write it to accept command line arguments for how the scripts should be run.

**Comment by sckilcoyne** [comment]
https://github.com/BostonCyclistsUnion/StressMap/pull/14

**Comment by sckilcoyne** [comment]
#18
